// What each Bandit level teaches, sourced from the summary list in
// content/posts/overthewire/bandit/walkthrough.md.
export const banditTeaches: Record<number, string> = {
  1: "Reading a dashed file",
  2: "Spaces in filenames",
  3: "Hidden files with ls -la",
  4: "Finding human-readable files",
  5: "Find file by size",
  6: "Find file by user and group",
  7: "Searching with grep",
  8: "Unique lines with sort and uniq",
  9: "Extracting strings from binary files",
  10: "Base64 decoding",
  11: "ROT13 with the tr command",
  12: "Hexdumps and decompression",
  13: "SSH login with a private key",
  14: "Netcat basics",
  15: "OpenSSL and encrypted connections",
  16: "Port scanning with Nmap",
  17: "Comparing files with diff",
  18: "SSH remote command execution",
  19: "SUID binary and Linux permissions",
  20: "Netcat listeners and SUID binary",
  21: "Cron jobs",
  22: "Cron jobs and bash scripting",
  23: "Cron jobs and bash scripting (continued)",
  24: "Brute forcing with bash and netcat",
  25: "Escaping restricted environments with more and vim",
  27: "Git - cloning a repository",
  28: "Git - log and checkout",
  29: "Git - branching",
  30: "Git - tags",
  31: "Git - push, commit, and .gitignore",
  32: "Environment variables and shell escape",
  33: "All levels complete!",
};
